### ISSUE TITLE
list of _links in Resource

### ISSUE THREAD

**Issue by francescobragagna** [LuvDaSun/angular-hal#28]
I'm just approccing now to your library, the code is clear, simple and clean. Thankyou. 
Sorry if my question seems to be rude, but I'm not so skilled in js.

During my application debug (chrome for example), I can not see the original element in _links property of returned object by the server. 

the Resource object generated and managed by the library has the new methods ($get, $post..) usefull to navigate relative entities, but it has removed the _links and _embedded objects from it. 

This is intentional, but why does not leave anyway them in the ojbect, for debug reason?
This could be usefull to know the related entities available for the object read.

**Comment by francescobragagna** [comment]
Ps.: i'm trying to change the library to do it, but I dont' know if that can have side effect.

**Comment by maennchen** [comment]
They're removed because they do not belong to the resource itself technically.
In my application i use a library to generate a patch between the original resource and a copy a user edited in a form. It would be a problem if the meta properties were there.

In the Pull Request #40, I added a new function which will allow you to retrieve meta properties.
